ChatXUsername: chat@bot.com
ChatXPassword: 'correct horse battery staple'
APIKey: jaoehoagheraghpreuihgape
site: 'interpersonal'
server: 'stackexchange' #Used as `https://chat.#{server}.com/chats/#{room_id}`
names: ['ips', '@ipscommentbot']
hq_room_id: 63296
all_comments: true
rooms: [63561, 61165]
ignore_user_ids: [36, 2625, 1599]
hot_seconds: 10800 #3hrs
hot_comment_num: 10 # 10 posts / hot_seconds
